Using TensorFlow backend.
/cluster/home/morathba/.local/lib64/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/cluster/home/morathba/.local/lib64/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/cluster/home/morathba/.local/lib64/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/cluster/home/morathba/.local/lib64/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
Loading dataframes...
Feature matrix already cached!
Feature matrix and labels created!

################# Calculating performance with hyperparameter tuning #################

Doing RandomizedSearchCV with n_iter=1000 for Decision Tree...
******** Scores of best 3 hyperparameter configurations ********
	Model with rank: 1
		Mean validation score: 0.649 (std: 0.023)
		Parameters: {'criterion': 'entropy', 'max_depth': 3, 'min_samples_leaf': 16, 'min_samples_split': 10, 'splitter': 'random'}
	Model with rank: 2
		Mean validation score: 0.648 (std: 0.026)
		Parameters: {'criterion': 'gini', 'max_depth': 4, 'min_samples_leaf': 4, 'min_samples_split': 18, 'splitter': 'random'}
	Model with rank: 3
		Mean validation score: 0.647 (std: 0.024)
		Parameters: {'criterion': 'entropy', 'max_depth': 3, 'min_samples_leaf': 6, 'min_samples_split': 11, 'splitter': 'random'}

Calculating performance of Decision Tree...
Barchart plot saved in file Plots/Performance/feature_importances.pdf
Traceback (most recent call last):
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/graphviz/backend.py", line 124, in render
    subprocess.check_call(args, startupinfo=STARTUPINFO, stderr=stderr)
  File "/cluster/apps/python/3.6.1/x86_64/lib64/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/cluster/apps/python/3.6.1/x86_64/lib64/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/cluster/apps/python/3.6.1/x86_64/lib64/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/cluster/apps/python/3.6.1/x86_64/lib64/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'dot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 296, in <module>
    main(args)
  File "main.py", line 111, in main
    do_write_to_file=False)
  File "/cluster/home/morathba/PP local/Code local/plunder planet/ML Model/model_factory.py", line 145, in get_performance
    plots_features.plot_graph_of_decision_classifier(model, X, y)
  File "/cluster/home/morathba/PP local/Code local/plunder planet/ML Model/plots_features.py", line 65, in plot_graph_of_decision_classifier
    graphviz.render('dot', 'pdf', 'decision_tree_graph')
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/graphviz/backend.py", line 127, in render
    raise ExecutableNotFound(args)
graphviz.backend.ExecutableNotFound: failed to execute ['dot', '-Tpdf', '-O', 'decision_tree_graph'], make sure the Graphviz executables are on your systems' PATH
