Sender: LSF System <lsfadmin@eu-ms-016-18>
Subject: Job 71023478: <python main.py -m 130> in cluster <euler> Exited

Job <python main.py -m 130> was submitted from host <eu-login-21-ng> by user <morathba> in cluster <euler> at Mon Aug 20 09:56:46 2018.
Job was executed on host(s) <eu-ms-016-18>, in queue <normal.4h>, as user <morathba> in cluster <euler> at Mon Aug 20 09:57:18 2018.
</cluster/home/morathba> was used as the home directory.
</cluster/home/morathba/4Ps-Plunder-Planet/4Ps> was used as the working directory.
Started at Mon Aug 20 09:57:18 2018.
Terminated at Mon Aug 20 09:57:28 2018.
Results reported at Mon Aug 20 09:57:28 2018.

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
python main.py -m 130
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   4.96 sec.
    Max Memory :                                 379 MB
    Average Memory :                             232.00 MB
    Total Requested Memory :                     1024.00 MB
    Delta Memory :                               645.00 MB
    Max Swap :                                   -
    Max Processes :                              3
    Max Threads :                                4
    Run time :                                   31 sec.
    Turnaround time :                            42 sec.

The output (if any) follows:

Using TensorFlow backend.
Loading dataframes...
Feature matrix already cached!
Feature matrix and labels created!

################# Get trained LSTM #################

Compiling lstm network...
Traceback (most recent call last):
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/keras/utils/vis_utils.py", line 27, in _check_pydot
    pydot.Dot.create(pydot.Dot())
AttributeError: 'NoneType' object has no attribute 'Dot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 172, in <module>
    main(_args)
  File "main.py", line 140, in main
    LSTM.get_finalscore(X, y, n_epochs=args.evaluate_lstm[0])
  File "/cluster/home/morathba/4Ps-Plunder-Planet/4Ps/LSTM.py", line 37, in get_finalscore
    roc_mean, f1_mean = get_performance_of_lstm_classifier(X, y, n_epochs, verbose, final_score=True)
  File "/cluster/home/morathba/4Ps-Plunder-Planet/4Ps/LSTM.py", line 71, in get_performance_of_lstm_classifier
    model = _generate_lstm_classifier((X_lstm.shape[1], X_lstm.shape[2]))
  File "/cluster/home/morathba/4Ps-Plunder-Planet/4Ps/LSTM.py", line 165, in _generate_lstm_classifier
    rankdir='TD')
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/keras/utils/vis_utils.py", line 135, in plot_model
    dot = model_to_dot(model, show_shapes, show_layer_names, rankdir)
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/keras/utils/vis_utils.py", line 56, in model_to_dot
    _check_pydot()
  File "/cluster/home/morathba/.local/lib64/python3.6/site-packages/keras/utils/vis_utils.py", line 31, in _check_pydot
    raise ImportError('Failed to import pydot. You must install pydot'
ImportError: Failed to import pydot. You must install pydot and graphviz for `pydotprint` to work.
